# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]


  [[redirects]]
  from = "http://localhost:3000/case-studies/earthly"
  to = "http://localhost:3000/case-studies"
  status = 301
  force = true