# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_IMAGE_DOMAIN_1 = "candid-cookie.flywheelsites.com"
  NEXT_PUBLIC_SITE_URL = "https://draft.dev"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add function configuration for API routes
[functions]
  node_bundler = "esbuild"
  included_files = ["public/**/*", ".next/server/**/*"]
  external_node_modules = ["sharp"]


# Keep your existing redirects
[[redirects]]
  from = "/case-studies/earthly"
  to = "/case-studies"
  status = 301
  force = true

  [[redirects]]
  from = "https://glittery-faun-4426fe.netlify.app/"
  to = "https://draft.dev"
  status = 301
  force = true
