# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-password-protection"

  [plugins.inputs]
    password = "52345"
    # Additional configurations if needed
